[package]
name = "pgmg"
version = "0.1.0"
edition = "2021"

[lib]
name = "pgmg"
path = "src/lib.rs"

[[bin]]
name = "pgmg"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.46.1", features = ["full"] }
tokio-postgres = { version = "0.7.13" }
postgres-types = { version = "0.2.9", features = ["derive"] }
futures-util = "0.3.31"
pg_query = "6.1.0"
regex = "1.10.2"
serde_json = "1.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }